# Site Settings
encoding                 : "utf-8"
locale                   : "en"
title                    : "Dan Carter's Faith Blog"
title_separator          : "-"
description              : ""
favicon                  : 
avatar                   : 
url                      : "https://faithblog.carterdan.net"
baseurl                  : 

# Site Author
author:
  name                   : "Dan Carter"

comments                 : true
disqus:
  shortname              : # sparrow-theme # https://help.disqus.com/customer/portal/articles/466208-what-s-a-shortname-

atom_feed:
  path                   : 

og_image                 : 

# Social sharing
twitter:
  username               : 

# Analytics
analytics:
  google:
    tracking_id          : 

# Reading Files
include:
  - _pages
# Files excluded from Jekyll builds
exclude:
- README.md
- LICENSE
- Gemfile
- Gemfile.lock


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /blog/:title/
paginate: 5 # amount of posts to show
paginate_path: "/blog/page:num/"
timezone: "Europe/London" # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Plugins
gems:
  - jekyll-paginate
  - jekyll-feed

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-feed


# Front matter defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: page
      comments: false
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      share: true